# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 480)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.twMainWindow = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twMainWindow.setFont(font)
        self.twMainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twMainWindow.setTabPosition(QtWidgets.QTabWidget.South)
        self.twMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.twMainWindow.setIconSize(QtCore.QSize(30, 30))
        self.twMainWindow.setElideMode(QtCore.Qt.ElideRight)
        self.twMainWindow.setUsesScrollButtons(False)
        self.twMainWindow.setMovable(False)
        self.twMainWindow.setTabBarAutoHide(True)
        self.twMainWindow.setObjectName("twMainWindow")
        self.tabTemperature = QtWidgets.QWidget()
        self.tabTemperature.setObjectName("tabTemperature")
        self.twTemperature = QtWidgets.QTabWidget(self.tabTemperature)
        self.twTemperature.setGeometry(QtCore.QRect(-1, -1, 801, 441))
        self.twTemperature.setTabPosition(QtWidgets.QTabWidget.East)
        self.twTemperature.setIconSize(QtCore.QSize(30, 30))
        self.twTemperature.setObjectName("twTemperature")
        self.tabTempData = QtWidgets.QWidget()
        self.tabTempData.setObjectName("tabTempData")
        self.tempPlot = QtWidgets.QWidget(self.tabTempData)
        self.tempPlot.setGeometry(QtCore.QRect(-1, -1, 761, 441))
        self.tempPlot.setObjectName("tempPlot")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IconGraph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twTemperature.addTab(self.tabTempData, icon, "")
        self.tabTempSettings = QtWidgets.QWidget()
        self.tabTempSettings.setObjectName("tabTempSettings")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabTempSettings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.dial_3 = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_3.setObjectName("dial_3")
        self.gridLayout.addWidget(self.dial_3, 2, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 5, 1, 1)
        self.dial_2 = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_2.setObjectName("dial_2")
        self.gridLayout.addWidget(self.dial_2, 1, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 7, 1, 1)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_4.sizePolicy().hasHeightForWidth())
        self.timeEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_4.setFont(font)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout.addWidget(self.timeEdit_4, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_3.setFont(font)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout.addWidget(self.timeEdit_3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IconCog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twTemperature.addTab(self.tabTempSettings, icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IconThermometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tabTemperature, icon2, "")
        self.tabLight = QtWidgets.QWidget()
        self.tabLight.setObjectName("tabLight")
        self.twLight = QtWidgets.QTabWidget(self.tabLight)
        self.twLight.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.twLight.setTabPosition(QtWidgets.QTabWidget.East)
        self.twLight.setIconSize(QtCore.QSize(30, 30))
        self.twLight.setObjectName("twLight")
        self.tabLightData = QtWidgets.QWidget()
        self.tabLightData.setObjectName("tabLightData")
        self.twLight.addTab(self.tabLightData, icon, "")
        self.tabLightSettings = QtWidgets.QWidget()
        self.tabLightSettings.setObjectName("tabLightSettings")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabLightSettings)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 761, 441))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 8, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 3, 1, 1)
        self.dial_4 = QtWidgets.QDial(self.gridLayoutWidget_2)
        self.dial_4.setObjectName("dial_4")
        self.gridLayout_2.addWidget(self.dial_4, 2, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 7, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 5, 1, 1)
        self.dial_5 = QtWidgets.QDial(self.gridLayoutWidget_2)
        self.dial_5.setObjectName("dial_5")
        self.gridLayout_2.addWidget(self.dial_5, 1, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 7, 1, 1)
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_5.sizePolicy().hasHeightForWidth())
        self.timeEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_5.setFont(font)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout_2.addWidget(self.timeEdit_5, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 1, 1, 1)
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_6.setFont(font)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.gridLayout_2.addWidget(self.timeEdit_6, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 3, 1, 1, 1)
        self.twLight.addTab(self.tabLightSettings, icon1, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IconLight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tabLight, icon3, "")
        self.tabWater = QtWidgets.QWidget()
        self.tabWater.setObjectName("tabWater")
        self.twWater = QtWidgets.QTabWidget(self.tabWater)
        self.twWater.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.twWater.setTabPosition(QtWidgets.QTabWidget.East)
        self.twWater.setIconSize(QtCore.QSize(30, 30))
        self.twWater.setObjectName("twWater")
        self.tabWaterData = QtWidgets.QWidget()
        self.tabWaterData.setObjectName("tabWaterData")
        self.twWater.addTab(self.tabWaterData, icon, "")
        self.tabWaterSettings = QtWidgets.QWidget()
        self.tabWaterSettings.setObjectName("tabWaterSettings")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tabWaterSettings)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 761, 441))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 8, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 2, 3, 1, 1)
        self.dial_6 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_6.setObjectName("dial_6")
        self.gridLayout_3.addWidget(self.dial_6, 2, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 5, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 7, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 5, 1, 1)
        self.dial_7 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_7.setObjectName("dial_7")
        self.gridLayout_3.addWidget(self.dial_7, 1, 6, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 2, 7, 1, 1)
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_7.sizePolicy().hasHeightForWidth())
        self.timeEdit_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_7.setFont(font)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.gridLayout_3.addWidget(self.timeEdit_7, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 2, 1, 1, 1)
        self.timeEdit_8 = QtWidgets.QTimeEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_8.setFont(font)
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.gridLayout_3.addWidget(self.timeEdit_8, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 3, 1, 1, 1)
        self.twWater.addTab(self.tabWaterSettings, icon1, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IconWater.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tabWater, icon4, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit.setGeometry(QtCore.QRect(160, 160, 118, 24))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit_2.setGeometry(QtCore.QRect(160, 230, 201, 151))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setCalendarPopup(True)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.spinBox = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox.setGeometry(QtCore.QRect(440, 120, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox.setGeometry(QtCore.QRect(530, 220, 68, 24))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.dial = QtWidgets.QDial(self.tab_4)
        self.dial.setGeometry(QtCore.QRect(610, 80, 101, 101))
        self.dial.setObjectName("dial")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IconClock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tab_4, icon5, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("IconSettings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tab_5, icon6, "")
        self.tabExit = QtWidgets.QWidget()
        self.tabExit.setObjectName("tabExit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabExit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 721, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.pbExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbExit.setObjectName("pbExit")
        self.horizontalLayout.addWidget(self.pbExit)
        self.pbReboot = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbReboot.setObjectName("pbReboot")
        self.horizontalLayout.addWidget(self.pbReboot)
        self.pbShutdown = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbShutdown.setObjectName("pbShutdown")
        self.horizontalLayout.addWidget(self.pbShutdown)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("IconShutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMainWindow.addTab(self.tabExit, icon7, "")
        self.verticalLayout.addWidget(self.twMainWindow)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.twMainWindow.setCurrentIndex(0)
        self.twTemperature.setCurrentIndex(0)
        self.twLight.setCurrentIndex(1)
        self.twWater.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GrowPi - MainWindow"))
        self.twTemperature.setTabText(self.twTemperature.indexOf(self.tabTempData), _translate("MainWindow", "Data"))
        self.label_2.setText(_translate("MainWindow", "Temperature Control"))
        self.pushButton.setText(_translate("MainWindow", "Fan On"))
        self.label_4.setText(_translate("MainWindow", "Timer On"))
        self.label_9.setText(_translate("MainWindow", "TempMax"))
        self.label_8.setText(_translate("MainWindow", "Auto Off"))
        self.label_3.setText(_translate("MainWindow", "Timer Control"))
        self.label.setText(_translate("MainWindow", "Manual Control"))
        self.pushButton_2.setText(_translate("MainWindow", "Fan Off"))
        self.label_10.setText(_translate("MainWindow", "TempMin"))
        self.label_7.setText(_translate("MainWindow", "Auto On"))
        self.label_5.setText(_translate("MainWindow", "Timer Off"))
        self.twTemperature.setTabText(self.twTemperature.indexOf(self.tabTempSettings), _translate("MainWindow", "Settings"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tabTemperature), _translate("MainWindow", "Temperature"))
        self.twLight.setTabText(self.twLight.indexOf(self.tabLightData), _translate("MainWindow", "Data"))
        self.label_6.setText(_translate("MainWindow", "Temperature Control"))
        self.pushButton_3.setText(_translate("MainWindow", "Fan On"))
        self.label_11.setText(_translate("MainWindow", "Timer On"))
        self.label_12.setText(_translate("MainWindow", "TempMax"))
        self.label_13.setText(_translate("MainWindow", "Auto Off"))
        self.label_14.setText(_translate("MainWindow", "Timer Control"))
        self.label_15.setText(_translate("MainWindow", "Manual Control"))
        self.pushButton_4.setText(_translate("MainWindow", "Fan Off"))
        self.label_16.setText(_translate("MainWindow", "TempMin"))
        self.label_17.setText(_translate("MainWindow", "Auto On"))
        self.label_18.setText(_translate("MainWindow", "Timer Off"))
        self.twLight.setTabText(self.twLight.indexOf(self.tabLightSettings), _translate("MainWindow", "Settings"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tabLight), _translate("MainWindow", "Light"))
        self.twWater.setTabText(self.twWater.indexOf(self.tabWaterData), _translate("MainWindow", "Data"))
        self.label_19.setText(_translate("MainWindow", "Temperature Control"))
        self.pushButton_5.setText(_translate("MainWindow", "Fan On"))
        self.label_20.setText(_translate("MainWindow", "Timer On"))
        self.label_21.setText(_translate("MainWindow", "TempMax"))
        self.label_22.setText(_translate("MainWindow", "Auto Off"))
        self.label_23.setText(_translate("MainWindow", "Timer Control"))
        self.label_24.setText(_translate("MainWindow", "Manual Control"))
        self.pushButton_6.setText(_translate("MainWindow", "Fan Off"))
        self.label_25.setText(_translate("MainWindow", "TempMin"))
        self.label_26.setText(_translate("MainWindow", "Auto On"))
        self.label_27.setText(_translate("MainWindow", "Timer Off"))
        self.twWater.setTabText(self.twWater.indexOf(self.tabWaterSettings), _translate("MainWindow", "Settings"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tabWater), _translate("MainWindow", "Water"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tab_4), _translate("MainWindow", "Clock"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tab_5), _translate("MainWindow", "Settings"))
        self.pbExit.setText(_translate("MainWindow", "Exit"))
        self.pbReboot.setText(_translate("MainWindow", "Reboot"))
        self.pbShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.twMainWindow.setTabText(self.twMainWindow.indexOf(self.tabExit), _translate("MainWindow", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
